create table portfolio_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text not null,
  live_url text not null,
  technologies text[] not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table portfolio_items enable row level security;

-- Create policies
create policy "Enable read access for all users" on portfolio_items
  for select using (true);

create policy "Enable insert for authenticated users only" on portfolio_items
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on portfolio_items
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on portfolio_items
  for delete using (auth.role() = 'authenticated');

-- Create function to automatically update updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Create trigger for updated_at
create trigger handle_updated_at
  before update on portfolio_items
  for each row
  execute function public.handle_updated_at(); 